---
services:
  loki:
    image: grafana/loki:2.9.17
    user: "0"
    command: -config.file=/etc/loki/config/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config/loki-config.yml:ro
      - ./loki-data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    user: "0"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=false
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped