http:
  routers:
    grafana:
      rule: "Host(`grafana.local.example.com`)"
      entryPoints:
        - websecure
      service: grafana
      tls:
        {}
    loki:
      rule: "Host(`loki.local.example.com`)"
      entryPoints:
        - websecure
      service: loki
      tls:
        {}
   
  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    loki:
      loadBalancer:
        servers:
          - url: "http://loki:3100"
          
  middlewares:
    admin-access:
      basicAuth:
        users:
          - "admin:PASSWORDHASHHERE"
